# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gems: [jekyll-paginate]

# Setup
title:               G40N
tagline:             'blog'
description:         'The blog about Hacking, Programming, Anime, etc.'
url:                 https://blog.gaonnr.me
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Junseop Ji
  url:               https://github.com/gaonnr
  email:             gaon0403@gmail.com

# Custom vars
version:             1.0.0
